- dávají najevo chybu která je zjištěna až při běhu
	- nejčastěji místa kde kompiler nemůže vědět stav dopředu
		- *Uživatelský vstup*
		- *Hardcoded proměnné*
- třída *Exception*
	- výjimky z této třídy dědí -> *DivideByZeroException, StackOverflow, IndexOutOfRangeException*
- zpětná vazba
- výjimky by se neměly stávat -> signál že bychom měli něco opravit
- možnost vytvářet vlastní

`DivideByZeroException` - při pokusu dělit nulou
```csharp
int zero = 0;

int x = 14 / zero; // Při spuštění dostaneme chybovou hlášku
```

### Odchytávání chyb
 - když předpokládáme že chyba může nastat -> nemusí fatálně ukončit chod programu
`try-catch`
```csharp
try {
	int zero = 0;
	
	int x = 14 / zero;
} catch {    // V případě že nastane chyba v "try" bloku
	Console.WriteLine("Ilegální operace"); 
}
```

```csharp
try {
	int[] arr = new int[3];
	int i = 5;
	
	int x = arr[i];
} catch (DivideByZeroException e) {  // Chytá jen DivideByZeroException
	Console.WriteLine(e.Message); 
}
```
*Tento program by vyvolal `IndexOutOfRangeException`, kvůli pokusu přistoupit k neexistujícímu indexu v poli*

### Vyvolání vlastní výjimky
`throw` - klíčové slovo pro vyvolání výjimky
```csharp
throw new Exception("Mám hlad!");
```

### Validace operací
- nejčastěji [[2. Konvence, klíčová slova, datové typy a třídění|konverze]]
- předchází výjimce
`TryParse()` - otestuje zda je operace (`true / false`) -> pokud `true`, může vrátit (`out`)
```csharp
string textValue = "5";
int intValue;

bool success = int.TryParse(textValue, out intValue);
```
*Pokud operace není možná `success` bude `false` a `intValue` nebude nastaveno*